### ISSUE TITLE
Убрать утечки памяти

### ISSUE THREAD

**Issue by selevit** [selevit/keymaster2#27]
Тут описан способ детекции утечек и причина их возникновения.

https://unspace.ca/dev/2013/avoiding-memory-leaks-in-backbone-js

На данном этапе нужно устранить утечки без использования сторонних garbage-коллекторов и в будущем следить за тем, чтобы не появлялись новые.

**Comment by stepler** [comment]
https://github.com/selevit/keymaster2/commit/22633bea18603f3e1d688709e0ca07e274f90a4d
